
extension HTTPMediaTypes {
    static var videoMediaTypes: [HTTPMediaType] {
        [
            .init("_1dInterleavedParityfec", "1d-interleaved-parityfec"),
            .init("_3gpp", "3gpp"),
            .init("_3gpp2", "3gpp2"),
            .init("_3gppTT", "3gpp-tt"),
            .init("av1", "AV1", fileExtensions: ["av1"]),
            .init("bmpeg", "BMPEG"),
            .init("bt656", "BT656"),
            .init("celB", "CelB"),
            .init("dv", "DV"),
            .init("encaprtp", ""),
            .init("enc", ""),
            .init("example", ""),
            .init("ffv1", "FFV1"),
            .init("flexfec", ""),
            .init("h261", "H261"),
            .init("h263", "H263"),
            .init("h263_2000", "H263-2000"),
            .init("h264", "h264"),
            .init("h264RCDO", "H264-RCDO"),
            .init("h264SVC", "H264SVC"),
            .init("h265", "H265"),
            .init("h266", "H266"),
            .init("isoSegment", "iso.segment"),
            .init("jpeg", "JPEG"),
            .init("jpeg2000", ""),
            .init("jxsv", ""),
            .init("matroska", ""),
            .init("matroska3d", "matroska-3d"),
            .init("mj2", ""),
            .init("mp1s", "MP1S"),
            .init("mp2p", "MP2P"),
            .init("mp2t", "MP2T"),
            .init("mp4", ""),
            .init("mp4VES", "MP4V-ES"),
            .init("mpv", "MPV"),
            .init("mpeg", "", fileExtensions: ["mpeg"]),
            .init("mpeg4Generic", "mpeg4-generic"),
            .init("nv", ""),
            .init("ogg", "", fileExtensions: ["ogg"]),
            .init("parityfec", ""),
            .init("pointer", ""),
            .init("quicktime", ""),
            .init("raptorfec", ""),
            .init("raw", ""),
            .init("rptEncAescm128", "rtp-enc-aescm128"),
            .init("rtploopback", ""),
            .init("rtx", ""),
            .init("scip", ""),
            .init("smpte291", ""),
            .init("smpte292m", "SMPTE292M"),
            .init("ulpfec", ""),
            .init("vc1", ""),
            .init("vc2", ""),

            .init("cctv", "vnd.CCTV"),
            .init("deceHD", "vnd.dece.hd"),
            .init("deceMobile", "vnd.dece.mobile"),
            .init("deceMP4", "vnd.dece.mp4"),
            .init("decePD", "vnd.dece.pd"),
            .init("deceSD", "vnd.dece.sd"),
            .init("deceVideo", "vnd.dece.video"),
            .init("directvMPEG", "vnd.directv.mpeg"),
            .init("directvMPEGTTS", "vnd.directv.mpegTTS"),
            .init("dlnaMpegTTS", "vnd.dlna.mpeg-tts"),
            .init("dvbFile", "vnd.dvb.file"),
            .init("fvt", "vnd.fvt"),
            .init("hnsVideo", "vnd.hns.video"),
            .init("iptvforum1dparityfec1010", "vnd.iptvforum.1dparityfec-1010"),
            .init("iptvforum1dparityfec2005", "vnd.iptvforum.1dparityfec-2005"),
            .init("iptvforum2dparityfec1010", "vnd.iptvforum.2dparityfec-1010"),
            .init("iptvforum2dparityfec2005", "vnd.iptvforum.2dparityfec-2005"),
            .init("iptvforumTTSAVC", "vnd.iptvforum.ttsavc"),
            .init("iptvforumTTSMPEG2", "vnd.iptvforum.ttsmpeg2"),
            .init("motorolaVideo", "vnd.motorola.video"),
            .init("motorolaVideop", "vnd.motorola.videop"),
            .init("mpegurl", "vnd.mpegurl"),
            .init("pyv", "vnd.ms-playready.media.pyv"),
            .init("nokiaInterleavedMultimedia", "vnd.nokia.interleaved-multimedia"),
            .init("nokiaMP4VR", "vnd.nokia.mp4vr"),
            .init("nokiaVideoVOIP", "vnd.nokia.videovoip"),
            .init("objectvideo", "vnd.objectvideo"),
            .init("radgamettoolsBink", "vnd.radgamettools.bink"),
            .init("radgamettoolsSmacker", "vnd.radgamettools.smacker"),
            .init("sealedMPEG1", "vnd.sealed.mpeg1"),
            .init("sealedMPEG4", "vnd.sealed.mpeg4"),
            .init("sealedSWF", "vnd.sealed.swf"),
            .init("sealedMediaSoftSealMOV", "vnd.sealedmedia.softseal.mov"),
            .init("uvvuMP4", "vnd.uvvu.mp4"),
            .init("youtubeYT", "vnd.youtube.yt"),
            .init("vivo", "vnd.vivo"),
            .init("vp8", "VP8"),
            .init("vp9", "VP9")
        ]
    }
}