
extension HTTPMediaTypes {
    static var textMediaTypes: [HTTPMediaType] {
        [
            .init("_1dInterleavedParityfec", "1d-interleaved-parityfec"),
            .init("cacheManifest", "cache-manifest"),
            .init("calendar", "", fileExtensions: ["ics"]),
            .init("cql", ""),
            .init("cqlExpression", "cql-expression"),
            .init("cqlIdentifier", "cql-identifier"),
            .init("css", ""),
            .init("csv", "", fileExtensions: ["csv"]),
            .init("csvSchema", "csv-schema"),
            .init("dns", ""),
            .init("encaprtp", ""),
            .init("enriched", ""),
            .init("example", ""),
            .init("fhirpath", ""),
            .init("flexfec", ""),
            .init("fwdred", ""),
            .init("gff3", ""),
            .init("grammarRefList", "grammar-ref-list"),
            .init("hl7v2", ""),
            .init("html", "", fileExtensions: ["html"]),
            .init("javascript", "", fileExtensions: ["js"]),
            .init("jcrCND", "jcr-cnd"),
            .init("markdown", "", fileExtensions: ["md", "markdown"]),
            .init("mizar", ""),
            .init("n3", "", fileExtensions: ["n3"]),
            .init("parameters", ""),
            .init("parityfec", ""),
            .init("plain", "", fileExtensions: ["txt"]),
            .init("provenanceNotation", "provenance-notation"),
            .init("prsFallensteinRST", "prs.fallenstein.rst"),
            .init("prsLinesTag", "prs.lines.tag"),
            .init("prsPropLogic", "prs.prop.logic"),
            .init("prsTexi", "prs.texi"),
            .init("raptorfec", ""),
            .init("red", "RED"),
            .init("rfc822Headers", "rfc822-headers"),
            .init("richtext", ""),
            .init("rtf", ""),
            .init("rtpEncAescm128", "rtp-enc-aescm128"),
            .init("rtploopback", ""),
            .init("rtx", ""),
            .init("sgml", "SGML"),
            .init("shaclc", ""),
            .init("shex", ""),
            .init("spdx", ""),
            .init("strings", ""),
            .init("t140", ""),
            .init("tabSeparatedValues", "tab-separated-values"),
            .init("troff", ""),
            .init("turtle", ""),
            .init("ulpfec", ""),
            .init("uriList", "uri-list"),
            .init("vcard", ""),

            .init("a", "vnd.a"),
            .init("abc", "vnd.abc"),
            .init("asciiArt", "vnd.ascii-art"),
            .init("curl", "vnd.curl"),
            .init("debianCopyright", "vnd.debian.copyright"),
            .init("dmClientScript", "vnd.DMClientScript"),
            .init("dvbSubtitle", "vnd.dvb.subtitle"),
            .init("esmertecThemeDescriptor", "vnd.esmertec.theme-descriptor"),
            .init("exchangeable", "vnd.exchangeable"),
            .init("familySearchGedcom", "vnd.familysearch.gedcom"),
            .init("ficlabFLT", "vnd.ficlab.flt"),
            .init("fmiFlexstor", "vnd.fmi.flexstor"),
            .init("gml", "vnd.gml"),
            .init("graphviz", "vnd.graphviz"),
            .init("hans", "vnd.hans"),
            .init("hgl", "vnd.hgl"),
            .init("in3d3dml", "vnd.in3d.3dml"),
            .init("in3dSpot", "vnd.in3d.spot"),
            .init("iptcNewsML", "vnd.IPTC.NewsML"),
            .init("iptcNITF", "vnd.IPTC.NITF"),
            .init("latexZ", "vnd.latex-z"),
            .init("motorolaReflex", "vnd.motorola.reflex"),
            .init("msMediapackage", "vnd.ms-mediapackage"),
            .init("net2phoneCommCenterCommand", "vnd.net2phone.commcenter.command"),
            .init("radisysMsmlBasicLayout", "vnd.radisys.msml-basic-layout"),
            .init("senxWarpscript", "vnd.senx.warpscript"),
            .init("sunJ2meAppDescriptor", "vnd.sun.j2me.app-descriptor"),
            .init("sosi", "vnd.sosi"),
            .init("trolltechLinguist", "vnd.trolltech.linguist"),
            .init("vcf", "vnd.vcf"),
            .init("wapSi", "vnd.wap.si"),
            .init("wapSl", "vnd.wap.sl"),
            .init("wapWmlscript", "vnd.wap.wmlscript"),
            .init("zooKCL", "vnd.zoo.kcl"),
            .init("vtt", ""),
            .init("wgsl", ""),
            .init("xml", "", fileExtensions: ["xml"]),
            .init("xmlExternalParsedEntity", "xml-external-parsed-entity")
        ]
    }
}