
extension MediaTypes {
    static var imageMediaTypes: [MediaType] {
        [
            .init("aces", ""),
            .init("apng", ""),
            .init("avci", ""),
            .init("avcs", ""),
            .init("avif", ""),
            .init("bmp", ""),
            .init("cgm", ""),
            .init("dicomRLE", "dicom-rle"),
            .init("dpx", ""),
            .init("emf", ""),
            .init("example", ""),
            .init("fits", ""),
            .init("g3fax", ""),
            .init("gif", "", fileExtensions: ["gif"]),
            .init("heic", ""),
            .init("heicSequence", "heic-sequence"),
            .init("heif", ""),
            .init("heifSequence", "heif-sequence"),
            .init("hej2k", ""),
            .init("ief", ""),
            .init("j2c", ""),
            .init("jls", ""),
            .init("jp2", ""),
            .init("jpeg", "", fileExtensions: ["jpeg", "jpg"]),
            .init("jph", ""),
            .init("jphc", ""),
            .init("jpm", ""),
            .init("jpx", ""),
            .init("jxl", ""),
            .init("jxr", ""),
            .init("jxrA", ""),
            .init("jxrS", ""),
            .init("jxs", ""),
            .init("jxsc", ""),
            .init("jxsi", ""),
            .init("jxss", ""),
            .init("ktx", ""),
            .init("ktx2", ""),
            .init("naplps", ""),
            .init("png", "", fileExtensions: ["png"]),
            .init("prsBTIF", "prs.btif"),
            .init("prsPTI", "prs.bti"),
            .init("pwgRaster", "pwg-raster"),
            .init("svgXML", "svg+xml"),
            .init("t38", ""),
            .init("tiff", ""),
            .init("tiffFX", "tiff-fx"),

            .init("psd", "vnd.adobe.photoshop"),
            .init("airzipAcceleratorAZV", "cnd.airzip.accelerator.azv"),
            .init("cnsINF2", "vnd.cns.inf2"),
            .init("deceGraphic", "vnd.dece.graphic"),
            .init("djvu", "vnd.djvu"),
            .init("dwg", "vnd.dwg"),
            .init("dxf", "vnd.dxf"),
            .init("dvbSubtitle", "vnd.dvb.subtitle"),
            .init("fastbidsheet", "vnd.fastbidsheet"),
            .init("fpx", "vnd.fpx"),
            .init("fst", "vnd.fst"),
            .init("fujixeroxEdmicsMMR", "vnd.fujixerox.edmics-mmr"),
            .init("fujixeroxEdmicsRLC", "vnd.fujixerox.edmics-rlc"),
            .init("globalGraphicsPGB", "vnd.globalgraphics.pgb"),
            .init("microsoftIcon", "vnd.microsoft.icon"),
            .init("mix", "vnd.mix"),
            .init("msModi", "vnd.ms-modi"),
            .init("mozillaAPNG", "vnd.mozilla.apng"),
            .init("netFPX", "vnd.net-fpx"),
            .init("pcoB16", "vnd.pco.b16"),
            .init("radiance", "vnd.radiance"),
            .init("sealedPNG", "vnd.sealed.png"),
            .init("sealedMediaSoftSealGIF", "vnd.sealedmedia.softseal.gif"),
            .init("sealedMediaSoftSealJPG", "vnd.sealedmedia.softseal.jpg"),
            .init("svf", "vnd.svf"),
            .init("tencentTap", "vnd.tencent.tap"),
            .init("vtf", "vnd.valve.source.texture"),
            .init("wapWBMP", "vnd.wap.wbmp"),
            .init("xiff", "vnd.xiff"),
            .init("zbrushPCX", "vnd.zbrush.pcx"),
            .init("webp", ""),
            .init("wmf", "")
        ]
    }
}